#!/usr/bin/env bash
#/ Usage: script/publish <package_directory> <nuget_api_key>
#/ Description: Publishes NuGet packages to NuGet.org.
#/ Options:
#/   <package_directory> - The directory containing the NuGet packages.
#/   <nuget_api_key> - The API key for NuGet.org.

source script/helpers/_utils.sh
set_source_and_root_dir

package_directory="$1"
nuget_api_key="$2"

for file in $(find "$package_directory" -type f -name "*.nupkg"); do
  dotnet nuget push $file --api-key $nuget_api_key --source https://api.nuget.org/v3/index.json --skip-duplicate
done