#!/usr/bin/env bash
#/ Usage: script/user-secrets [<options>]
#/ Description: Manages user secrets for the sample web project - HogTied.Web.
#/ Arguments:
#/   <options> - Options to pass to the dotnet user-secrets command
#/ Example: To list all user secrets:
#/   script/user-secrets list
#/
#/   To set a user secret:
#/   script/user-secrets set <key> <value

source script/helpers/_utils.sh
set_source_and_root_dir

dotnet user-secrets --project samples/HogTied.Web/HogTied.Web.csproj "$@"